version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.13

    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "64:58:56:6b:e9:88:c9:07:1e:56:4a:96:d0:f1:05:90"
      - checkout
      - run:
          name: Deploy to GCP for SSH
          command: |
            cd ./scripts
            ls -la
            sudo chmod 777 ./deploy.sh
            ls -la
            ssh $SSH_USER@$SSH_HOST 'bash -i < ./deploy.sh'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
